### PR TITLE
Create vite/react app from template, remove default content

### PR DESCRIPTION
**Pull request by maahsnd**

### CODE REVIEW

**Comment by maahsnd** [comment]
@joelbarton-io @DONTSTOPLOVINGMEBABY Review please

**Comment by DONTSTOPLOVINGMEBABY** [comment]
Will clone and check it out now

**Comment by DONTSTOPLOVINGMEBABY** [comment]
It looks good to me. I like that it's a completely bare application. I think that's going to give us a really solid starting point to decide on what kind of packages we want to use and allow us flexibility on designing the initial structure. 

One thing I did notice is that there are a few deprecated libraries when building with Vite's ```npm create vite``` tool. I don't think this is a problem given that all applications built with the latest version of Vite are built with these packages. It's more so something that we will have to keep up with as we work within the Vite ecosystem. 

:)

**Review by DONTSTOPLOVINGMEBABY — APPROVED** [review]
It looks good to me. I like that it's a completely bare application. I think that's going to give us a really solid starting point to decide on what kind of packages we want to use and allow us flexibility on designing the initial structure.

One thing I did notice is that there are a few deprecated libraries when building with Vite's npm create vite tool. I don't think this is a problem given that all applications built with the latest version of Vite are built with these packages. It's more so something that we will have to keep up with as we work within the Vite ecosystem.

:)

**Pull request merged**
